### ISSUE TITLE
Custom Refreshing Time

### ISSUE THREAD

**Issue by jordanleven** [jordanleven/force-refresh#3]
[From WordPress Plugins Forum user Quebro (@quebro)](https://wordpress.org/support/topic/customize-refreshing-time/):

> This plugin is just great!
> 
> But it would be greater if I could customize the time. So, instead of refreshing the site within two minutes, I can decide to refresh it within two seconds after I click the REFRESH BOTTON, for example.
> 
> Are you planning on adding that feature?
> Thanks!

**Comment by atolloweb** [comment]
Thanks for your response!

So, this is what I am trying to do:
I need to create a trivia game for my students. I am thinking about creating a simple page with a few questions on a WordPress password protected PAGE, like example.com/trivia.

I need them to always stay in just one page for the whole game. They will have less than 20 seconds to answer each question. Only when I decide that they are ready for the second question, I will refresh the page/site, so they will see the second question (in fact - while they take time to answer - I will be adding the next question ON THE SAME TRIVIA PAGE ). And I think that 2 minutes from the time I click on REFRESH is too much. I will hardly have control of the the game.
I would like them to see the updated content right when I click on REFRESH (or even 2/3 seconds later).
Does it make sense?

There will be 15/20 devices connected on that trivia page, plus other people surfing on the rest of the site.

Now, I was thinking that maybe the option to refresh just one page (instead of the whole site) after 2/3 seconds I click on REFRESH, it can be a solution. So, only those 15 devices will have refreshed the page. Do you think this will crash the site?
If not, what do you think about adding a box, on the right of each wordpress page, where it says: PUBLISH, PAGE ATTRIBUTE, FEATERED IMAGE, etc....adding something like: SECONDS FOR THIS PAGE TO BE REFRESHED. So, every time I click on the button REFRESH SITE, it will only refresh the pages according to the secs they have.
I don't know. It can be an idea, but it can be different too. I am just trying to give you a hint.

Or, instead of having example.com/TRIVIA as page, I can create a subfolder with a whole new password protected wordpress site (and a brand new database). So, when the site /TRIVIA will be refreshed, it won't affect the main one: example.com/

What do you think? Which one of the solution do you think that will work?

Thanks so muuuch!

**Comment by atolloweb** [comment]
Hi Jordan,

You are right, the refresh won't be at the same time for all the participants. So, web sockets might be a solution. I completely trust you :)

Yes, I am available for beta test. Just let me know when!
