### ISSUE TITLE
Add refresh on sleeping mobile

### ISSUE THREAD

**Issue by zipitrik** [jordanleven/force-refresh#458]
### Which area are you seeing an issue with

Sleeping mobile don't refresh

### What type of issue are you reporting

- [ ] Incorrect/Unexpected behavior
- [ ] Data loss or security issue
- [ ] Plugin crash
- [ ] Plugin slow or unresponsive
- [x] Feature request or enhancement

## Current Behavior
If
- a cellphone has a webpage open,
- and the cellphone goes to sleep,
- and the webpage is updated and refreshed,
- and the phone is woke up after . 
then the update will not show.

I don't think it's a bug , because that is "normal" behavior in the sense that it is how mobile browser work , but it would be great if this "issue" could be somehow "fixed".

Best would be the web page to check for updates and cache new content even when the device is in sleep mode. When the user returns to the web page, the updated content can be displayed.

But if it's not possible, then maybe some king of idle check can be done and an auto-force-refresh can be done when the mobile comes out of idle.

Thanks

## Steps to Reproduce

1. open webpage on mobile
2. let mobile goes to sleep
3. trigger a force refresh
4. wake up phone
5. see the outdated page

**Comment by jordanleven** [comment]
Hey @zipitrik - this is behavior that is unallowed by mobile browsers. The only option to wake a device would be by summoning a user via a notification, which the user would have to approve prior. Since this introduces additional overhead for an edge case, this isn't something I'd be looking to introduce on the horizon. Force Refresh is, however, an open-source project so if you have a proof of concept or would like to fork this repo to customize it yourself, feel free!
